server:
  # 设置tomcat
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 50
  # 指定端口
  port: 8080
  # 指定项目的ContextPath路径
  servlet:
    context-path: /food

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 包含dao的yml配置文件,对应的是application-xxx.yml文件的xxx名称
  profiles:
    include: dao

